name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          # Pass environment variables needed for the build, e.g., API keys
          # Ensure these are set as GitHub Secrets if they are sensitive
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The directory where Vite outputs the build files
          # The branch to publish to. Common choices are 'gh-pages' or 'main' (if configured for docs folder)
          publish_branch: gh-pages